apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alerts.monitoring.rancher.io
spec:
  group: monitoring.rancher.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: alerts
    singular: alert
    kind: Alert



    