apiVersion: monitoring.rancher.io/v1beta1
kind: Alert
metadata:
  name: alert1
  labels:
    environment: default
spec:
  name: asd
  sendResolved: false
  severity: critical
  object: service
  objecID: 1s1
  serviceRule:
    unhealthyPercentage: 80
  recipientID: testabc
  recipientType: email
  



    