apiVersion: monitoring.rancher.io/v1beta1
kind: Alert
metadata:
  name: uuid
  labels:
    environment: default
spec:
  description: asd
  sendResolved: false
  severity: critical
  object: pod
  objecID: 1s1
  podRule:
    expectState: running
  serviceRule:
    unhealthyPercentage: 80
  recipientID: testabc
  



    