apiVersion: monitoring.rancher.io/v1beta1
kind: Alert
metadata:
  name: uuid

description: asd
severity: critical
targetType: pod/node/deployment/statefulSet/daemonSet
targetId: 1s1
nodeRule: 
  condition: NotReady/DiskPressure/MemoryPressure/OutOfDisk
deploymentRule:
  unavailablePercentage: 60
daemonSetRule:
  unavailablePercentage: 60
statefulSetRule:
  unavailablePercentage: 60
  
advancedOptions:
  groupWait:  "30s"
  groupInterval: "5m"
  repeatInterval: "4h"

recipientId: testabc
  



    