apiVersion: monitoring.rancher.io/v1beta1
kind: Alert
metadata:
  name: uuid
  labels:
    environment: default
spec:
  description: asd
  sendResolved: false
  severity: critical
  object: custom
  objecID: 1s1
  customAlertRule:
      rate(http_url) > 100 
  serviceRule:
    unhealthyPercentage: 80
  recipientID: testabc
  



    