apiVersion: monitoring.rancher.io/v1beta1
kind: Notifier
metadata:
  name: notifier3
  labels:
    environment: default
    type: email
spec:
  type: email
  emailConfig:
    smtpAuthIdentity: ffdfdsfrueireuirefsdrerer
    smtpAuthPassword: '123456'
    smtpAuthSecret: fdfserfrereioiofiodsfsdfsdfio
    smtpAuthUsername: viky
    smtpFrom: rancher@mail.com
    smtpRequiredTls: false
    smtpSmartHost: '127.0.0.1'
