apiVersion: monitoring.rancher.io/v1beta1
kind: Notifier
metadata:
  name: notifier-email
  
emailConfig:
  smtpAuthIdentity: identity1
  smtpAuthPassword: abc123
  smtpAuthSecret: secretsxxx
  smtpAuthUsername: viky
  smtpFrom: zion@rancher.coom
  smtpRequiredTls: false
  smtpSmartHost: '127.0.0.1'
slackConfig:
  slackApiUrl: zion.slack.com
pagerdutyConfig:
  pagerdutyUrl: zion123.pagerduty.com

    
