apiVersion: monitoring.rancher.io/v1beta1
kind: Notifier
metadata:
  name: notifier-email
  labels:
    environment: default
    type: email
spec:
  emailConfig:
    smtpAuthIdentity: identity1
    smtpAuthPassword: abc123
    smtpAuthSecret: secretsxxx
    smtpAuthUsername: viky
    smtpFrom: zion@rancher.coom
    smtpRequiredTls: false
    smtpSmartHost: '127.0.0.1'
---
apiVersion: monitoring.rancher.io/v1beta1
kind: Notifier
metadata:
  name: notifier-slack
  labels:
    environment: default
    type: slack
spec:
  slackConfig:
    slackApiUrl: zion.slack.com
---
apiVersion: monitoring.rancher.io/v1beta1
kind: Notifier
metadata:
  name: notifier-pagerduty
  labels:
    environment: default
    type: pagerduty
spec:
  pagerdutyConfig:
    pagerdutyUrl: zion.pagerduty.com

    
