apiVersion: monitoring.rancher.io/v1beta1
kind: Notifier
metadata:
  name: notifier-email
  
resolveTimeout: 5h
emailConfig:
  #  smtpAuthIdentity: identity1
  smtpAuthPassword:  <secret>
  #  smtpAuthSecret: secretsxxx
  smtpAuthUsername: viky
  # smtpFrom: zion@rancher.coom
  # smtpRequiredTls: false
  smtpSmartHost: '127.0.0.1'
slackConfig:
  slackApiUrl:  <secret>
pagerdutyConfig:
  pagerdutyUrl: zion123.pagerduty.com

    
