kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: alertmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.11.0
        args:
        - -config.file=/etc/alertmanager/config.yml
        - -storage.path=/alertmanager
        ports:
        - name: webui2
          hostPort: 9093
          containerPort: 9093
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 150Mi
        volumeMounts:
        - mountPath: /alertmanager
          name: data
        - mountPath: /etc/alertmanager
          name: config-volume
      volumes:
      - emptyDir: {}
        name: data
      - secret:
          secretName: alertmanager-config
        name: config-volume
