global:
    slack_api_url: '<slack_webhook_url>'
    pagerduty_url: https://events.pagerduty.com/generic/2010-04-15/create_event.json
    

route:
    receiver: 'rancherlas'
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 30s
receivers:
    - name: 'rancherlas'
      slack_configs:
      - channel: '#alerts'
