kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager

data:
  config.yml: Z2xvYmFsOgogICAgc2xhY2tfYXBpX3VybDogJzxzbGFja193ZWJob29rX3VybD4nCnRlbXBsYXRlczoKICAgIC0gJy9ldGMvYWxlcnRtYW5hZ2VyLXRlbXBsYXRlcy8qLnRtcGwnCnJvdXRlOgogICAgcmVjZWl2ZXI6ICdyYW5jaGVybGFzJwogICAgZ3JvdXBfd2FpdDogMTBzCiAgICBncm91cF9pbnRlcnZhbDogMTBzCiAgICByZXBlYXRfaW50ZXJ2YWw6IDMwcwpyZWNlaXZlcnM6CiAgICAtIG5hbWU6ICdyYW5jaGVybGFzJwogICAgICBzbGFja19jb25maWdzOgogICAgICAtIGNoYW5uZWw6ICcjYWxlcnRzJw==
